### ISSUE TITLE
Document known-good requirements?

### ISSUE THREAD

**Issue by artob** [ChrisTheBaron/cylon-rolling-spider#15]
After installing [stable](https://nodejs.org/en/download/) Node and NPM versions (4.6.0 and 2.15.9, respectively) on a fresh Ubuntu 16.04 LTS box, and doing `npm install cylon-rolling-spider`, the example from the README fails as follows:

```
$ sudo node example.js 
2016-09-28T16:01:28.699Z : [Robot 1] - Starting connections.
2016-09-28T16:01:28.704Z : [Robot 1] - Starting connection 'rolling-spider'.
2016-09-28T16:01:28.705Z : [Robot 1] - Starting devices.
2016-09-28T16:01:28.706Z : [Robot 1] - Starting device 'drone'.
/home/jhacker/node_modules/cylon-rolling-spider/node_modules/rolling-spider/lib/drone.js:166
      } else if ((typeof this.targets === 'undefined' || this.targets.length === 0) && isDrone) {
                                                                     ^

TypeError: Cannot read property 'length' of null
    at null.<anonymous> (/home/jhacker/node_modules/cylon-rolling-spider/node_modules/rolling-spider/lib/drone.js:166:70)
    at emitOne (events.js:77:13)
    at Noble.emit (events.js:169:7)
    at Noble.onDiscover (/home/jhacker/node_modules/cylon-rolling-spider/node_modules/rolling-spider/node_modules/noble/lib/noble.js:135:10)
    at emitMany (events.js:108:13)
    at emit (events.js:182:7)
    at NobleBindings.onDiscover (/home/jhacker/node_modules/cylon-rolling-spider/node_modules/rolling-spider/node_modules/noble/lib/hci-socket/bindings.js:169:10)
    at emitMany (events.js:108:13)
    at emit (events.js:182:7)
    at Gap.onHciLeAdvertisingReport (/home/jhacker/node_modules/cylon-rolling-spider/node_modules/rolling-spider/node_modules/noble/lib/hci-socket/gap.js:223:10)
```

@ChrisTheBaron, would you expect this project to still work with current versions of Ubuntu (16.04), Node (4.6.0), BlueZ (5.3.7 on 16.04), Noble (1.7.0), and node-rolling-spider?

**Comment by artob** [comment]
Ping?

**Comment by nilz3ro** [comment]
Ping? @ChrisTheBaron. @bendiken did you find the solution to this?
